// Curated catalog for the special-character picker (SpecialCharPicker.svelte).
// Glyphs are chosen to render in Liberation Serif / Times New Roman so the
// on-screen preview matches the exported .odt. `name` is lowercase for search.

export interface SpecialChar {
  char: string;
  /** Lowercase descriptive name, matched as a substring by the search box. */
  name: string;
}

export interface CharCategory {
  name: string;
  chars: SpecialChar[];
}

export const CHAR_CATEGORIES: CharCategory[] = [
  {
    name: 'Punctuation',
    chars: [
      { char: '—', name: 'em dash' },
      { char: '–', name: 'en dash' },
      { char: '‐', name: 'hyphen' },
      { char: '…', name: 'ellipsis horizontal' },
      { char: '·', name: 'middle dot interpunct' },
      { char: '•', name: 'bullet' },
      { char: '‣', name: 'triangular bullet' },
      { char: '¡', name: 'inverted exclamation mark' },
      { char: '¿', name: 'inverted question mark' },
      { char: '§', name: 'section sign' },
      { char: '¶', name: 'pilcrow paragraph sign' },
      { char: '†', name: 'dagger' },
      { char: '‡', name: 'double dagger' },
      { char: '‖', name: 'double vertical line' },
      { char: '¦', name: 'broken bar' },
      { char: '«', name: 'left guillemet angle quote' },
      { char: '»', name: 'right guillemet angle quote' },
      { char: '‹', name: 'single left angle quote' },
      { char: '›', name: 'single right angle quote' },
      { char: '“', name: 'left double quotation mark' },
      { char: '”', name: 'right double quotation mark' },
      { char: '„', name: 'double low-9 quotation mark' },
      { char: '‘', name: 'left single quotation mark' },
      { char: '’', name: 'right single quotation mark apostrophe' },
      { char: '‚', name: 'single low-9 quotation mark' },
      { char: '′', name: 'prime minutes feet' },
      { char: '″', name: 'double prime seconds inches' },
      { char: '‴', name: 'triple prime' },
      { char: '※', name: 'reference mark' },
      { char: '⁂', name: 'asterism' },
    ],
  },
  {
    name: 'Currency',
    chars: [
      { char: '€', name: 'euro' },
      { char: '£', name: 'pound sterling' },
      { char: '¥', name: 'yen yuan' },
      { char: '¢', name: 'cent' },
      { char: '$', name: 'dollar' },
      { char: '¤', name: 'currency sign generic' },
      { char: '₩', name: 'won' },
      { char: '₹', name: 'indian rupee' },
      { char: '₽', name: 'ruble' },
      { char: '₺', name: 'turkish lira' },
      { char: '₴', name: 'hryvnia' },
      { char: '₦', name: 'naira' },
      { char: '₱', name: 'peso' },
      { char: '฿', name: 'baht' },
      { char: '₪', name: 'new shekel' },
      { char: '₫', name: 'dong' },
      { char: '₨', name: 'rupee sign' },
    ],
  },
  {
    name: 'Math',
    chars: [
      { char: '±', name: 'plus minus' },
      { char: '∓', name: 'minus or plus' },
      { char: '×', name: 'multiplication times' },
      { char: '÷', name: 'division obelus' },
      { char: '−', name: 'minus sign' },
      { char: '≠', name: 'not equal to' },
      { char: '≤', name: 'less than or equal to' },
      { char: '≥', name: 'greater than or equal to' },
      { char: '≈', name: 'almost equal approximately' },
      { char: '≡', name: 'identical to equivalent' },
      { char: '∝', name: 'proportional to' },
      { char: '∞', name: 'infinity' },
      { char: '√', name: 'square root radical' },
      { char: '∛', name: 'cube root' },
      { char: '∑', name: 'n-ary summation sigma' },
      { char: '∏', name: 'n-ary product pi' },
      { char: '∫', name: 'integral' },
      { char: '∂', name: 'partial differential' },
      { char: '∆', name: 'increment delta' },
      { char: '∇', name: 'nabla del gradient' },
      { char: '∈', name: 'element of' },
      { char: '∉', name: 'not an element of' },
      { char: '⊂', name: 'subset of' },
      { char: '⊃', name: 'superset of' },
      { char: '∪', name: 'union' },
      { char: '∩', name: 'intersection' },
      { char: '∧', name: 'logical and' },
      { char: '∨', name: 'logical or' },
      { char: '¬', name: 'not sign negation' },
      { char: '∀', name: 'for all universal' },
      { char: '∃', name: 'there exists' },
      { char: '∅', name: 'empty set' },
      { char: '∥', name: 'parallel to' },
      { char: '⊥', name: 'perpendicular up tack' },
      { char: '∠', name: 'angle' },
      { char: '°', name: 'degree' },
      { char: '′', name: 'prime' },
      { char: 'µ', name: 'micro mu' },
      { char: '‰', name: 'per mille' },
      { char: '‱', name: 'per ten thousand basis point' },
      { char: '½', name: 'one half fraction' },
      { char: '⅓', name: 'one third fraction' },
      { char: '⅔', name: 'two thirds fraction' },
      { char: '¼', name: 'one quarter fraction' },
      { char: '¾', name: 'three quarters fraction' },
      { char: '⅛', name: 'one eighth fraction' },
      { char: '¹', name: 'superscript one' },
      { char: '²', name: 'superscript two squared' },
      { char: '³', name: 'superscript three cubed' },
      { char: '⁰', name: 'superscript zero' },
    ],
  },
  {
    name: 'Arrows',
    chars: [
      { char: '←', name: 'leftwards arrow left' },
      { char: '→', name: 'rightwards arrow right' },
      { char: '↑', name: 'upwards arrow up' },
      { char: '↓', name: 'downwards arrow down' },
      { char: '↔', name: 'left right arrow horizontal' },
      { char: '↕', name: 'up down arrow vertical' },
      { char: '↖', name: 'north west arrow up left' },
      { char: '↗', name: 'north east arrow up right' },
      { char: '↘', name: 'south east arrow down right' },
      { char: '↙', name: 'south west arrow down left' },
      { char: '⇐', name: 'leftwards double arrow' },
      { char: '⇒', name: 'rightwards double arrow implies' },
      { char: '⇑', name: 'upwards double arrow' },
      { char: '⇓', name: 'downwards double arrow' },
      { char: '⇔', name: 'left right double arrow iff' },
      { char: '↩', name: 'leftwards arrow with hook' },
      { char: '↪', name: 'rightwards arrow with hook' },
      { char: '↻', name: 'clockwise open circle arrow' },
      { char: '↺', name: 'anticlockwise open circle arrow' },
      { char: '✓', name: 'check mark tick' },
      { char: '✗', name: 'ballot x cross' },
    ],
  },
  {
    name: 'Greek',
    chars: [
      { char: 'Α', name: 'capital alpha' },
      { char: 'Β', name: 'capital beta' },
      { char: 'Γ', name: 'capital gamma' },
      { char: 'Δ', name: 'capital delta' },
      { char: 'Ε', name: 'capital epsilon' },
      { char: 'Ζ', name: 'capital zeta' },
      { char: 'Η', name: 'capital eta' },
      { char: 'Θ', name: 'capital theta' },
      { char: 'Ι', name: 'capital iota' },
      { char: 'Κ', name: 'capital kappa' },
      { char: 'Λ', name: 'capital lambda' },
      { char: 'Μ', name: 'capital mu' },
      { char: 'Ν', name: 'capital nu' },
      { char: 'Ξ', name: 'capital xi' },
      { char: 'Ο', name: 'capital omicron' },
      { char: 'Π', name: 'capital pi' },
      { char: 'Ρ', name: 'capital rho' },
      { char: 'Σ', name: 'capital sigma' },
      { char: 'Τ', name: 'capital tau' },
      { char: 'Υ', name: 'capital upsilon' },
      { char: 'Φ', name: 'capital phi' },
      { char: 'Χ', name: 'capital chi' },
      { char: 'Ψ', name: 'capital psi' },
      { char: 'Ω', name: 'capital omega' },
      { char: 'α', name: 'alpha' },
      { char: 'β', name: 'beta' },
      { char: 'γ', name: 'gamma' },
      { char: 'δ', name: 'delta' },
      { char: 'ε', name: 'epsilon' },
      { char: 'ζ', name: 'zeta' },
      { char: 'η', name: 'eta' },
      { char: 'θ', name: 'theta' },
      { char: 'ι', name: 'iota' },
      { char: 'κ', name: 'kappa' },
      { char: 'λ', name: 'lambda' },
      { char: 'μ', name: 'mu' },
      { char: 'ν', name: 'nu' },
      { char: 'ξ', name: 'xi' },
      { char: 'ο', name: 'omicron' },
      { char: 'π', name: 'pi' },
      { char: 'ρ', name: 'rho' },
      { char: 'σ', name: 'sigma' },
      { char: 'ς', name: 'final sigma' },
      { char: 'τ', name: 'tau' },
      { char: 'υ', name: 'upsilon' },
      { char: 'φ', name: 'phi' },
      { char: 'χ', name: 'chi' },
      { char: 'ψ', name: 'psi' },
      { char: 'ω', name: 'omega' },
    ],
  },
  {
    name: 'Latin',
    chars: [
      { char: 'À', name: 'capital a grave' },
      { char: 'Á', name: 'capital a acute' },
      { char: 'Â', name: 'capital a circumflex' },
      { char: 'Ã', name: 'capital a tilde' },
      { char: 'Ä', name: 'capital a umlaut diaeresis' },
      { char: 'Å', name: 'capital a ring' },
      { char: 'Æ', name: 'capital ae ligature' },
      { char: 'Ç', name: 'capital c cedilla' },
      { char: 'È', name: 'capital e grave' },
      { char: 'É', name: 'capital e acute' },
      { char: 'Ê', name: 'capital e circumflex' },
      { char: 'Ë', name: 'capital e umlaut diaeresis' },
      { char: 'Ì', name: 'capital i grave' },
      { char: 'Í', name: 'capital i acute' },
      { char: 'Î', name: 'capital i circumflex' },
      { char: 'Ï', name: 'capital i umlaut diaeresis' },
      { char: 'Ñ', name: 'capital n tilde' },
      { char: 'Ò', name: 'capital o grave' },
      { char: 'Ó', name: 'capital o acute' },
      { char: 'Ô', name: 'capital o circumflex' },
      { char: 'Õ', name: 'capital o tilde' },
      { char: 'Ö', name: 'capital o umlaut diaeresis' },
      { char: 'Ø', name: 'capital o slash stroke' },
      { char: 'Œ', name: 'capital oe ligature' },
      { char: 'Ù', name: 'capital u grave' },
      { char: 'Ú', name: 'capital u acute' },
      { char: 'Û', name: 'capital u circumflex' },
      { char: 'Ü', name: 'capital u umlaut diaeresis' },
      { char: 'Ý', name: 'capital y acute' },
      { char: 'Ÿ', name: 'capital y umlaut diaeresis' },
      { char: 'à', name: 'a grave' },
      { char: 'á', name: 'a acute' },
      { char: 'â', name: 'a circumflex' },
      { char: 'ã', name: 'a tilde' },
      { char: 'ä', name: 'a umlaut diaeresis' },
      { char: 'å', name: 'a ring' },
      { char: 'æ', name: 'ae ligature' },
      { char: 'ç', name: 'c cedilla' },
      { char: 'è', name: 'e grave' },
      { char: 'é', name: 'e acute' },
      { char: 'ê', name: 'e circumflex' },
      { char: 'ë', name: 'e umlaut diaeresis' },
      { char: 'ì', name: 'i grave' },
      { char: 'í', name: 'i acute' },
      { char: 'î', name: 'i circumflex' },
      { char: 'ï', name: 'i umlaut diaeresis' },
      { char: 'ñ', name: 'n tilde enye' },
      { char: 'ò', name: 'o grave' },
      { char: 'ó', name: 'o acute' },
      { char: 'ô', name: 'o circumflex' },
      { char: 'õ', name: 'o tilde' },
      { char: 'ö', name: 'o umlaut diaeresis' },
      { char: 'ø', name: 'o slash stroke' },
      { char: 'œ', name: 'oe ligature' },
      { char: 'ù', name: 'u grave' },
      { char: 'ú', name: 'u acute' },
      { char: 'û', name: 'u circumflex' },
      { char: 'ü', name: 'u umlaut diaeresis' },
      { char: 'ý', name: 'y acute' },
      { char: 'ÿ', name: 'y umlaut diaeresis' },
      { char: 'ß', name: 'sharp s eszett' },
    ],
  },
  {
    name: 'Symbols',
    chars: [
      { char: '©', name: 'copyright' },
      { char: '®', name: 'registered trademark' },
      { char: '™', name: 'trademark tm' },
      { char: '℗', name: 'sound recording copyright' },
      { char: '№', name: 'numero number sign' },
      { char: '℃', name: 'degrees celsius' },
      { char: '℉', name: 'degrees fahrenheit' },
      { char: 'Ω', name: 'ohm' },
      { char: '°', name: 'degree sign' },
      { char: '℠', name: 'service mark sm' },
      { char: '★', name: 'black star filled' },
      { char: '☆', name: 'white star outline' },
      { char: '♠', name: 'spade suit' },
      { char: '♣', name: 'club suit' },
      { char: '♥', name: 'heart suit' },
      { char: '♦', name: 'diamond suit' },
      { char: '♪', name: 'eighth note music' },
      { char: '♫', name: 'beamed eighth notes music' },
      { char: '✔', name: 'heavy check mark' },
      { char: '✘', name: 'heavy ballot x' },
      { char: '☑', name: 'ballot box with check' },
      { char: '☐', name: 'ballot box empty' },
      { char: '✓', name: 'tick checkmark' },
      { char: '☞', name: 'pointing hand right' },
      { char: '✉', name: 'envelope mail' },
      { char: '☎', name: 'telephone' },
      { char: '⚑', name: 'flag' },
      { char: '⚘', name: 'flower' },
      { char: ' ', name: 'non-breaking space nbsp' },
    ],
  },
];
